# Generated by Django 5.2.7 on 2025-10-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        # Add performance indexes for events
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_events_location ON events (venue);",
            reverse_sql="DROP INDEX IF EXISTS idx_events_location;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_events_datetime_range ON events (start_datetime, end_datetime);",
            reverse_sql="DROP INDEX IF EXISTS idx_events_datetime_range;"
        ),
        # Add full-text search index for events (SQLite compatible)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_events_title_search ON events (title);",
            reverse_sql="DROP INDEX IF EXISTS idx_events_title_search;"
        ),
        # Add indexes for ticket types
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_ticket_types_availability ON ticket_types (quantity_available, quantity_sold);",
            reverse_sql="DROP INDEX IF EXISTS idx_ticket_types_availability;"
        ),
        # Add indexes for discounts
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_discounts_validity ON discounts (valid_from, valid_until, is_active);",
            reverse_sql="DROP INDEX IF EXISTS idx_discounts_validity;"
        ),
    ]
