# Generated by Django 5.2.7 on 2025-10-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0001_initial'),
    ]

    operations = [
        # Add performance indexes for theaters
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_theaters_location ON theaters (city, state);",
            reverse_sql="DROP INDEX IF EXISTS idx_theaters_location;"
        ),
        # Add indexes for movies
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_movies_title_search ON movies (title);",
            reverse_sql="DROP INDEX IF EXISTS idx_movies_title_search;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_movies_genre_rating ON movies (genre, rating);",
            reverse_sql="DROP INDEX IF EXISTS idx_movies_genre_rating;"
        ),
        # Add indexes for showtimes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_showtimes_datetime ON showtimes (start_time, end_time);",
            reverse_sql="DROP INDEX IF EXISTS idx_showtimes_datetime;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_showtimes_availability ON showtimes (available_seats, total_seats);",
            reverse_sql="DROP INDEX IF EXISTS idx_showtimes_availability;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_showtimes_theater_movie ON showtimes (theater_id, movie_id);",
            reverse_sql="DROP INDEX IF EXISTS idx_showtimes_theater_movie;"
        ),
    ]
