# Generated by Django 5.2.7 on 2025-10-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theaters', '0002_auto_20251010_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='booked_seats',
            field=models.JSONField(blank=True, default=list, help_text='List of booked seat identifiers'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='seating_layout',
            field=models.JSONField(blank=True, default=dict, help_text='Seating configuration for each screen'),
        ),
    ]
