# Generated by Django 5.2.7 on 2025-10-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Seat number/identifier (for movie bookings)', max_length=10, null=True),
        ),
    ]
