# Generated by Django 5.2.7 on 2025-10-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_ticket_seat_number'),
    ]

    operations = [
        # Add performance indexes for bookings
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_bookings_customer_status ON bookings (customer_id, booking_status);",
            reverse_sql="DROP INDEX IF EXISTS idx_bookings_customer_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_bookings_payment_status ON bookings (payment_status, booking_status);",
            reverse_sql="DROP INDEX IF EXISTS idx_bookings_payment_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_bookings_datetime ON bookings (created_at, updated_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_bookings_datetime;"
        ),
        # Add indexes for tickets
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tickets_booking_status ON tickets (booking_id, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_tickets_booking_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_tickets_validation ON tickets (ticket_number, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_tickets_validation;"
        ),
    ]
