# Generated by Django 5.2.7 on 2025-10-13 08:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20251010_1443'),
        ('events', '0002_auto_20251010_1442'),
        ('theaters', '0003_alter_showtime_booked_seats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField(blank=True)),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.CharField(blank=True, max_length=100)),
                ('quantity_requested', models.PositiveIntegerField(default=1)),
                ('max_price_willing_to_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('expired', 'Expired'), ('fulfilled', 'Fulfilled')], default='active', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'waitlist_entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_custome_59c648_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_booking_4d53ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_booking_0b59a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_payment_3ea9ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_booking_ab1f8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_event_i_d1c541_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_showtim_35a66d_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_created_118d3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_booking_98f7e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_ticket__4c9624_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_status_fbbf05_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_ticket__eed111_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_seat_nu_7e5faa_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='applied_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='events.discount'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('event', 'Event Booking'), ('movie', 'Movie Booking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='theaters.showtime'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('valid', 'Valid'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='valid', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.tickettype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='used_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='events.event'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='theaters.showtime'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='events.tickettype'),
        ),
    ]
